import React, { useState, useRef, useEffect } from 'react'
import { Video, Square, Play, Pause, MapPin, Clock, Share2, Save, Trash2 } from 'lucide-react'
import Card from '../components/Card'
import Button from '../components/Button'
import Input from '../components/Input'
import { useApp } from '../contexts/AppContext'

const IncidentRecorder = () => {
  const { 
    isRecording, 
    setIsRecording, 
    addIncidentRecord, 
    incidentRecords,
    setIncidentRecords
  } = useApp()
  
  const [recordingTime, setRecordingTime] = useState(0)
  const [location, setLocation] = useState('')
  const [currentRecord, setCurrentRecord] = useState(null)
  const [userNotes, setUserNotes] = useState('')
  const [shareableContent, setShareableContent] = useState('')
  const [showHistory, setShowHistory] = useState(false)
  
  const mediaRecorderRef = useRef(null)
  const chunksRef = useRef([])
  const timerRef = useRef(null)

  // Get user location when component mounts
  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          const { latitude, longitude } = position.coords
          setLocation(`${latitude.toFixed(6)}, ${longitude.toFixed(6)}`)
        },
        (error) => {
          console.error('Error getting location:', error)
          setLocation('Location not available')
        }
      )
    }
  }, [])

  // Timer effect for recording
  useEffect(() => {
    if (isRecording) {
      timerRef.current = setInterval(() => {
        setRecordingTime(prev => prev + 1)
      }, 1000)
    } else {
      if (timerRef.current) {
        clearInterval(timerRef.current)
      }
    }

    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current)
      }
    }
  }, [isRecording])

  const startRecording = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: true,
        audio: true
      })

      mediaRecorderRef.current = new MediaRecorder(stream)
      chunksRef.current = []

      mediaRecorderRef.current.ondataavailable = (event) => {
        if (event.data.size > 0) {
          chunksRef.current.push(event.data)
        }
      }

      mediaRecorderRef.current.onstop = () => {
        const blob = new Blob(chunksRef.current, { type: 'video/webm' })
        const url = URL.createObjectURL(blob)
        
        const record = {
          gpsLocation: location,
          recordingUrl: url,
          userNotes: '',
          duration: recordingTime
        }
        
        setCurrentRecord(record)
        stream.getTracks().forEach(track => track.stop())
      }

      mediaRecorderRef.current.start()
      setIsRecording(true)
      setRecordingTime(0)
    } catch (error) {
      console.error('Error starting recording:', error)
      alert('Unable to start recording. Please check your camera and microphone permissions.')
    }
  }

  const stopRecording = () => {
    if (mediaRecorderRef.current && isRecording) {
      mediaRecorderRef.current.stop()
      setIsRecording(false)
    }
  }

  const saveIncident = () => {
    if (currentRecord) {
      const savedRecord = addIncidentRecord({
        ...currentRecord,
        userNotes,
        shareableContentUrl: shareableContent
      })
      
      setCurrentRecord(null)
      setUserNotes('')
      setShareableContent('')
      setRecordingTime(0)
      
      alert('Incident saved successfully!')
    }
  }

  const generateShareableContent = () => {
    if (currentRecord) {
      const timestamp = new Date().toLocaleString()
      const content = `Incident Report - ${timestamp}
Location: ${currentRecord.gpsLocation}
Duration: ${Math.floor(recordingTime / 60)}:${(recordingTime % 60).toString().padStart(2, '0')}
Notes: ${userNotes || 'No additional notes'}

Generated by Gavel Guard - Know Your Rights`
      
      setShareableContent(content)
    }
  }

  const shareContent = () => {
    if (shareableContent) {
      if (navigator.share) {
        navigator.share({
          title: 'Incident Report',
          text: shareableContent
        })
      } else {
        navigator.clipboard.writeText(shareableContent)
        alert('Content copied to clipboard!')
      }
    }
  }

  const deleteIncident = (recordId) => {
    setIncidentRecords(prev => prev.filter(record => record.recordId !== recordId))
  }

  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60)
    const secs = seconds % 60
    return `${mins}:${secs.toString().padStart(2, '0')}`
  }

  return (
    <div className="p-4 lg:p-8 max-w-7xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-2xl lg:text-3xl font-bold text-gray-900 mb-2 flex items-center">
          <Video className="w-8 h-8 text-red-500 mr-3" />
          Incident Recorder
        </h1>
        <p className="text-gray-600">
          Discreetly record police interactions with automatic logging and sharing capabilities.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Recording Controls */}
        <div className="space-y-6">
          {/* Main Recording Card */}
          <Card className="p-6">
            <div className="text-center">
              {isRecording ? (
                <div className="mb-6">
                  <div className="w-24 h-24 bg-red-500 rounded-full flex items-center justify-center mx-auto mb-4 animate-pulse">
                    <Square className="w-8 h-8 text-white" />
                  </div>
                  <div className="text-2xl font-bold text-red-600 mb-2">
                    {formatTime(recordingTime)}
                  </div>
                  <p className="text-red-600 font-medium">Recording in progress</p>
                </div>
              ) : (
                <div className="mb-6">
                  <div className="w-24 h-24 bg-gray-200 rounded-full flex items-center justify-center mx-auto mb-4">
                    <Video className="w-8 h-8 text-gray-400" />
                  </div>
                  <p className="text-gray-600">Ready to record</p>
                </div>
              )}

              <div className="space-y-4">
                {!isRecording ? (
                  <Button 
                    onClick={startRecording}
                    variant="destructive"
                    size="lg"
                    className="w-full"
                  >
                    <Play className="w-5 h-5 mr-2" />
                    Start Recording
                  </Button>
                ) : (
                  <Button 
                    onClick={stopRecording}
                    variant="outline"
                    size="lg"
                    className="w-full"
                  >
                    <Square className="w-5 h-5 mr-2" />
                    Stop Recording
                  </Button>
                )}
              </div>
            </div>
          </Card>

          {/* Location Info */}
          <Card className="p-6">
            <h3 className="font-semibold text-gray-900 mb-4 flex items-center">
              <MapPin className="w-5 h-5 text-green-500 mr-2" />
              Location Information
            </h3>
            <div className="space-y-3">
              <div className="flex items-center text-sm text-gray-600">
                <Clock className="w-4 h-4 mr-2" />
                <span>{new Date().toLocaleString()}</span>
              </div>
              <div className="flex items-center text-sm text-gray-600">
                <MapPin className="w-4 h-4 mr-2" />
                <span>{location || 'Getting location...'}</span>
              </div>
            </div>
          </Card>

          {/* Quick Rights Reminder */}
          <Card className="p-6 bg-blue-50 border-blue-200">
            <h3 className="font-semibold text-blue-900 mb-3">
              Quick Rights Reminder
            </h3>
            <ul className="text-blue-800 text-sm space-y-1">
              <li>• You have the right to record police interactions</li>
              <li>• You have the right to remain silent</li>
              <li>• You can refuse consent to searches</li>
              <li>• Ask "Am I free to leave?"</li>
            </ul>
          </Card>
        </div>

        {/* Current Recording / History */}
        <div className="space-y-6">
          {currentRecord ? (
            /* Current Recording Details */
            <Card className="p-6">
              <h3 className="font-semibold text-gray-900 mb-4">
                Recording Completed
              </h3>
              
              <div className="space-y-4">
                <div className="aspect-video bg-gray-100 rounded-lg flex items-center justify-center">
                  <video 
                    src={currentRecord.recordingUrl} 
                    controls 
                    className="w-full h-full rounded-lg"
                  />
                </div>
                
                <Input
                  label="Additional Notes"
                  placeholder="Add any important details about the interaction..."
                  value={userNotes}
                  onChange={(e) => setUserNotes(e.target.value)}
                />
                
                <div className="flex space-x-3">
                  <Button onClick={saveIncident} className="flex-1">
                    <Save className="w-4 h-4 mr-2" />
                    Save Incident
                  </Button>
                  <Button 
                    onClick={generateShareableContent}
                    variant="outline"
                  >
                    <Share2 className="w-4 h-4 mr-2" />
                    Generate Summary
                  </Button>
                </div>
                
                {shareableContent && (
                  <div className="mt-4">
                    <textarea
                      value={shareableContent}
                      onChange={(e) => setShareableContent(e.target.value)}
                      className="w-full p-3 border rounded-md text-sm"
                      rows={6}
                    />
                    <Button 
                      onClick={shareContent}
                      variant="outline"
                      size="sm"
                      className="mt-2"
                    >
                      Share Content
                    </Button>
                  </div>
                )}
              </div>
            </Card>
          ) : (
            /* Incident History */
            <Card className="p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold text-gray-900">
                  Incident History
                </h3>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setShowHistory(!showHistory)}
                >
                  {showHistory ? 'Hide' : 'Show'} History
                </Button>
              </div>
              
              {showHistory && (
                <div className="space-y-3">
                  {incidentRecords.length === 0 ? (
                    <div className="text-center py-8">
                      <Video className="w-12 h-12 text-gray-300 mx-auto mb-4" />
                      <p className="text-gray-500">No incidents recorded yet</p>
                    </div>
                  ) : (
                    incidentRecords.map((record) => (
                      <div key={record.recordId} className="border rounded-lg p-4 hover:bg-gray-50">
                        <div className="flex items-center justify-between">
                          <div>
                            <div className="font-medium text-gray-900">
                              {new Date(record.timestamp).toLocaleDateString()}
                            </div>
                            <div className="text-sm text-gray-500 flex items-center">
                              <MapPin className="w-3 h-3 mr-1" />
                              {record.gpsLocation || 'Location not available'}
                            </div>
                            {record.userNotes && (
                              <div className="text-sm text-gray-600 mt-1">
                                {record.userNotes.substring(0, 100)}...
                              </div>
                            )}
                          </div>
                          <div className="flex space-x-2">
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => deleteIncident(record.recordId)}
                            >
                              <Trash2 className="w-4 h-4" />
                            </Button>
                          </div>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              )}
            </Card>
          )}
        </div>
      </div>

      {/* Important Notice */}
      <Card className="p-6 mt-8 bg-yellow-50 border-yellow-200">
        <div className="flex items-start">
          <div className="w-6 h-6 text-yellow-600 mr-3 flex-shrink-0 mt-0.5">
            ⚠️
          </div>
          <div>
            <h3 className="font-semibold text-yellow-800 mb-2">
              Important Recording Guidelines
            </h3>
            <ul className="text-yellow-700 text-sm space-y-1">
              <li>• Record from a reasonable distance that doesn't interfere with police duties</li>
              <li>• Stay calm and avoid drawing attention to your recording</li>
              <li>• Do not use flash or make recording obvious unless necessary</li>
              <li>• Save recordings immediately to prevent accidental deletion</li>
              <li>• Share incident summaries with trusted contacts or legal aid if needed</li>
            </ul>
          </div>
        </div>
      </Card>
    </div>
  )
}

export default IncidentRecorder